CREATE TABLE usuarios (
     id BIGINT GENERATED ALWAYS AS IDENTITY,
     nome VARCHAR(100) NOT NULL,
     email VARCHAR(100) NOT NULL UNIQUE,
     cpf VARCHAR(11) NOT NULL UNIQUE,
     telefone VARCHAR(20) NOT NULL,
     PRIMARY KEY (id)
);
